name: Automate Preprocessing

# Trigger: Jalan setiap kali ada push ke branch main
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write  # Memberi izin Action untuk push balik ke repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Ambil kode dari repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Siapkan Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 3. Install library yang dibutuhkan
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Jalankan Script Otomatisasi
    - name: Run Preprocessing Script
      run: |
        python preprocessing/automate_[Nama-Anda].py

    # 5. Commit dan Push data hasil proses kembali ke GitHub
    - name: Commit and Push changes
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        
        # Tambahkan file hasil preprocessing
        git add preprocessing/fraud_detection_preprocessing/
        
        # Cek apakah ada perubahan sebelum commit
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update processed data" && git push)